spring.application.name=backend
server.port=${PORT:8080}
spring.datasource.url=jdbc:postgresql:///rockpaper_db?cloudSqlInstance=project-adeeae9e-06bc-474a-ad3:asia-south1:rpsdb&socketFactory=com.google.cloud.sql.postgres.SocketFactory
spring.datasource.username=postgres
spring.datasource.password=Aswin2704@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false