spring.application.name=backend
server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://34.93.6.211:5432/rockpaper_db

spring.datasource.username=postgres
spring.datasource.password=Aswin2704@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false